version: '3'
services:
  master:
    image: redis
    container_name: redis-master
    command: redis-server  --requirepass zxcde@1  --masterauth zxcde@1
    ports:
      - 6380:6379
    networks:
      vpcbr:
        ipv4_address: 172.23.0.2
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6381:6379
    networks:
      vpcbr:
        ipv4_address: 172.23.0.3
    command:  redis-server --slaveof redis-master 6379 --masterauth zxcde@1  --requirepass zxcde@1
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6382:6379
    networks:
      vpcbr:
        ipv4_address: 172.23.0.4
    command: redis-server --slaveof redis-master 6379 --masterauth zxcde@1 --requirepass zxcde@1

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.23.0.0/16
         gateway: 172.23.0.1