version: '3'
services:
  master:
    image: redis
    container_name: redis-master
    command: redis-server  --requirepass zxcde@1  --masterauth zxcde@1
    ports:
      - 6380:6379
    networks:
      vpcbr:
        ipv4_address: 172.23.0.2
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6381:6379
    networks:
      vpcbr:
        ipv4_address: 172.23.0.3
    command:  redis-server --slaveof redis-master 6379 --masterauth zxcde@1  --requirepass zxcde@1
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6382:6379
    networks:
      vpcbr:
        ipv4_address: 172.23.0.4
    command: redis-server --slaveof redis-master 6379 --masterauth zxcde@1 --requirepass zxcde@1
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      vpcbr:
        ipv4_address: 172.23.0.5
  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    ports:
    - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      vpcbr:
        ipv4_address: 172.23.0.6
  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      vpcbr:
        ipv4_address: 172.23.0.7

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.23.0.0/16
         gateway: 172.23.0.1