version: '3'
services:
  master:
    image: redis
    container_name: redis-master
    command: redis-server  --requirepass test@123  --masterauth test@123   --replica-announce-ip 180.76.0.2   --replica-announce-port  6380 
    ports:
      - 6380:6379
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6381:6379
    command:  redis-server --slaveof redis-master 6379 --masterauth test@123  --requirepass test@123  --replica-announce-ip 180.76.0.3  --replica-announce-port  6381
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6382:6379
    command: redis-server --slaveof redis-master 6379 --masterauth test@123 --requirepass test@123  --replica-announce-ip 180.76.0.4  --replica-announce-port  6382

